# Generated by CMake, DO NOT EDIT
/Users/benutzer/Documents/anSim/framework/CG_AnSim_demos/BUILD_Xcode/CMakeFiles/cmake.check_cache: \
/Users/benutzer/Documents/anSim/framework/cmake/DefaultLibrary.cmake\
/Users/benutzer/Documents/anSim/framework/libraries/rollercoaster/CMakeLists.txt
	/opt/local/bin/cmake -H/Users/benutzer/Documents/anSim/framework/CG_AnSim_demos/src -B/Users/benutzer/Documents/anSim/framework/CG_AnSim_demos/BUILD_Xcode
